"""パターンプラクティスプロンプト - Section 7.4

ビジネス英語パターンの生成・評価用プロンプトと
初期パターンデータベース（200+パターン）。
"""


def build_pattern_generation_prompt(
    category: str,
    level: str = "B2",
    weak_patterns: list[str] | None = None,
) -> str:
    """
    パターン練習エクササイズ生成用のシステムプロンプトを構築

    Args:
        category: パターンカテゴリ
        level: 目標CEFRレベル
        weak_patterns: ユーザーの弱点パターンリスト

    Returns:
        システムプロンプト文字列
    """
    category_guidance = {
        "meeting": "Focus on meeting facilitation, agenda management, decision making, and action item assignment.",
        "negotiation": "Focus on proposal making, counter-offers, conditional language, concessions, and closing deals.",
        "presentation": "Focus on opening hooks, transitions, data interpretation, Q&A handling, and conclusions.",
        "email": "Focus on formal requests, follow-ups, apologies, scheduling, and professional closings.",
        "discussion": "Focus on opinion expression, agreement/disagreement, debate, and consensus building.",
        "general": "Mix of various business communication patterns for well-rounded practice.",
    }

    guidance = category_guidance.get(category, category_guidance["general"])

    weak_pattern_note = ""
    if weak_patterns:
        patterns_str = ", ".join(weak_patterns)
        weak_pattern_note = f"""
## User's Weak Areas
The user has struggled with these patterns recently: {patterns_str}
Please include exercises that specifically target these weak areas to reinforce learning.
"""

    return f"""You are a Business English pattern drill generator for FluentEdge AI.

## Task
Generate pattern practice exercises for Japanese business professionals learning English.
Each exercise should focus on a specific business English pattern or expression.

## Target Level: CEFR {level}
## Category: {category}
{guidance}

{weak_pattern_note}

## Exercise Design

### Types of Exercises
1. **Fill-in-the-blank**: Provide a sentence with a blank for the key pattern element
2. **Complete the pattern**: Provide a pattern template and ask user to create a full sentence
3. **Transform**: Provide a casual version and ask for the business-appropriate version

### Requirements
- Each exercise must focus on a practical, high-frequency business pattern
- Include natural Japanese translations as hints
- Patterns should be immediately usable in real business situations
- Vary between formal and semi-formal registers
- Progress from simpler to more complex patterns within the set

## Output Format
Return ONLY a JSON array of exercises:
[
    {{
        "pattern_id": "cat-001",
        "pattern_template": "I would like to ___ the meeting.",
        "example_sentence": "I would like to adjourn the meeting until tomorrow.",
        "japanese_hint": "会議を___したいのですが。（例：明日まで延期）",
        "category": "{category}",
        "difficulty": "{level}",
        "fill_in_blank": true
    }}
]

## Rules
- Generate exactly the number of exercises requested
- pattern_id format: category abbreviation + 3-digit number (e.g., "mtg-001")
- Each pattern should be distinct and commonly used in business
- Japanese hints should clarify meaning without giving away the English answer
- Return ONLY valid JSON, no markdown formatting"""


def build_pattern_check_prompt() -> str:
    """
    パターン回答チェック用のシステムプロンプトを構築

    Returns:
        システムプロンプト文字列
    """
    return """You are a Business English pattern evaluator for FluentEdge AI. Your task is to evaluate a user's answer against the expected pattern usage.

## Evaluation Criteria

### Scoring (0.0 to 1.0)
- **1.0**: Perfect match - correct pattern usage with appropriate vocabulary
- **0.8-0.9**: Minor variations that are equally correct (synonyms, slight wording differences)
- **0.6-0.7**: Pattern used correctly but with grammar or vocabulary issues
- **0.4-0.5**: Partial understanding of the pattern shown but incorrect usage
- **0.2-0.3**: Significant misunderstanding of the pattern
- **0.0-0.1**: Completely incorrect or unrelated answer

### is_correct Threshold
- true if score >= 0.7

### Evaluation Focus
1. **Pattern accuracy**: Is the target business English pattern used correctly?
2. **Grammatical correctness**: Is the grammar correct in the context of the pattern?
3. **Register appropriateness**: Is the formality level appropriate for business use?
4. **Contextual fit**: Does the answer make sense in a business context?

## Output Format
Return ONLY a JSON object:
{
    "is_correct": true/false,
    "score": 0.0-1.0,
    "corrected": "The best corrected version using the target pattern",
    "explanation": "Brief explanation of what was good/wrong",
    "usage_tip": "A practical tip for using this pattern in real business situations"
}

## Rules
- Accept valid alternative completions if they demonstrate correct pattern usage
- The corrected field should show the best version close to the user's attempt
- usage_tip should be actionable and specific to the pattern
- Explanation should be concise (1-3 sentences)
- Return ONLY valid JSON"""


# ビジネス英語パターンの初期データベース（200+パターン）
BUSINESS_PATTERNS: dict[str, list[dict]] = {
    "meeting": [
        {
            "id": "mtg-001",
            "template": "Let's get started with ___.",
            "example": "Let's get started with the quarterly review.",
            "japanese": "___から始めましょう。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-002",
            "template": "I'd like to bring up ___.",
            "example": "I'd like to bring up the budget allocation issue.",
            "japanese": "___について取り上げたいのですが。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-003",
            "template": "Could we move on to ___?",
            "example": "Could we move on to the next agenda item?",
            "japanese": "___に移ってもよろしいでしょうか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-004",
            "template": "I'd like to propose that we ___.",
            "example": "I'd like to propose that we extend the deadline by two weeks.",
            "japanese": "___することを提案したいのですが。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-005",
            "template": "Does anyone have any objections to ___?",
            "example": "Does anyone have any objections to the proposed timeline?",
            "japanese": "___に異議のある方はいらっしゃいますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-006",
            "template": "To summarize what we've discussed, ___.",
            "example": "To summarize what we've discussed, we'll proceed with Option B.",
            "japanese": "議論をまとめますと、___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-007",
            "template": "I think we need to circle back to ___.",
            "example": "I think we need to circle back to the compliance issue.",
            "japanese": "___に戻る必要があると思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-008",
            "template": "Let me play devil's advocate here — ___.",
            "example": "Let me play devil's advocate here — what if the market doesn't recover?",
            "japanese": "あえて反対意見を述べますと — ___。",
            "register": "semi-formal",
            "cefr": "C1",
        },
        {
            "id": "mtg-009",
            "template": "Could you elaborate on ___?",
            "example": "Could you elaborate on the risk mitigation strategy?",
            "japanese": "___についてもう少し詳しく説明していただけますか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-010",
            "template": "I'd like to second ___'s point about ___.",
            "example": "I'd like to second Sarah's point about customer retention.",
            "japanese": "___さんの___についてのご意見に賛成です。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-011",
            "template": "Before we wrap up, let's confirm the action items: ___.",
            "example": "Before we wrap up, let's confirm the action items: John will draft the proposal by Friday.",
            "japanese": "終了前にアクションアイテムを確認しましょう：___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-012",
            "template": "I'm afraid we're running short on time, so ___.",
            "example": "I'm afraid we're running short on time, so let's table this for the next meeting.",
            "japanese": "時間が足りなくなってきたので、___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-013",
            "template": "Just to clarify, are you suggesting that ___?",
            "example": "Just to clarify, are you suggesting that we restructure the entire department?",
            "japanese": "確認ですが、___ということでしょうか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-014",
            "template": "Building on what ___ said, I think ___.",
            "example": "Building on what Tom said, I think we should also consider the European market.",
            "japanese": "___さんの発言に加えて、___と思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-015",
            "template": "I appreciate your input, but I'd like to suggest an alternative: ___.",
            "example": "I appreciate your input, but I'd like to suggest an alternative: we could outsource the initial phase.",
            "japanese": "ご意見ありがとうございますが、代替案を提案させてください：___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "mtg-016",
            "template": "Let's take a step back and look at the bigger picture: ___.",
            "example": "Let's take a step back and look at the bigger picture: our long-term growth strategy.",
            "japanese": "一歩引いて全体像を見ましょう：___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-017",
            "template": "Could we schedule a follow-up meeting to discuss ___?",
            "example": "Could we schedule a follow-up meeting to discuss the implementation details?",
            "japanese": "___について話し合うフォローアップ会議を設定できますか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-018",
            "template": "I'd like to table ___ for now and revisit it ___.",
            "example": "I'd like to table this topic for now and revisit it next week.",
            "japanese": "___は一旦保留にして、___に再度取り上げたいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-019",
            "template": "If there are no further questions, let's ___.",
            "example": "If there are no further questions, let's adjourn the meeting.",
            "japanese": "他にご質問がなければ、___しましょう。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-020",
            "template": "I believe we've reached a consensus on ___.",
            "example": "I believe we've reached a consensus on the new pricing structure.",
            "japanese": "___について合意に達したと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-021",
            "template": "With all due respect, I disagree with ___ because ___.",
            "example": "With all due respect, I disagree with that assessment because the data suggests otherwise.",
            "japanese": "失礼ですが、___に同意しかねます。理由は___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "mtg-022",
            "template": "That's a valid point. However, we should also consider ___.",
            "example": "That's a valid point. However, we should also consider the impact on our existing customers.",
            "japanese": "もっともなご指摘です。ただし、___も考慮すべきです。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-023",
            "template": "Going forward, I recommend that we ___.",
            "example": "Going forward, I recommend that we conduct monthly performance reviews.",
            "japanese": "今後は、___することを推奨します。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-024",
            "template": "Can we get everyone's buy-in on ___?",
            "example": "Can we get everyone's buy-in on the revised project timeline?",
            "japanese": "___について皆さんの合意を得られますか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-025",
            "template": "I'd like to assign ___ as the owner of this action item.",
            "example": "I'd like to assign Maria as the owner of this action item.",
            "japanese": "このアクションアイテムの担当者として___さんを指名したいと思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-026",
            "template": "Let's do a quick round-robin. ___, would you like to start?",
            "example": "Let's do a quick round-robin. David, would you like to start?",
            "japanese": "順番に意見を聞きましょう。___さん、最初にどうぞ。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-027",
            "template": "I'd like to open the floor to ___.",
            "example": "I'd like to open the floor to questions from the team.",
            "japanese": "___を受け付けたいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-028",
            "template": "To put this in perspective, ___.",
            "example": "To put this in perspective, our competitor launched a similar product last quarter.",
            "japanese": "これを文脈で考えると、___。",
            "register": "semi-formal",
            "cefr": "C1",
        },
        {
            "id": "mtg-029",
            "template": "The key takeaway from today's meeting is ___.",
            "example": "The key takeaway from today's meeting is that we need to accelerate our digital transformation.",
            "japanese": "本日の会議の要点は___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-030",
            "template": "I'll send out the meeting minutes by ___.",
            "example": "I'll send out the meeting minutes by end of day.",
            "japanese": "___までに議事録を送付します。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "mtg-031",
            "template": "Thank you all for your contributions. Let's reconvene on ___.",
            "example": "Thank you all for your contributions. Let's reconvene on Thursday at 2 PM.",
            "japanese": "皆さんのご協力ありがとうございます。___に再度集まりましょう。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-032",
            "template": "I think we're getting off track. Let's refocus on ___.",
            "example": "I think we're getting off track. Let's refocus on the main objective.",
            "japanese": "脱線しているようです。___に集中しましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-033",
            "template": "For the record, I'd like to note that ___.",
            "example": "For the record, I'd like to note that the legal team has approved this approach.",
            "japanese": "記録のため、___を申し添えます。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "mtg-034",
            "template": "I'm not entirely convinced. Could you walk me through ___?",
            "example": "I'm not entirely convinced. Could you walk me through the financial projections?",
            "japanese": "まだ完全には納得できていません。___を詳しく説明していただけますか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "mtg-035",
            "template": "Let's park that idea and come back to it when ___.",
            "example": "Let's park that idea and come back to it when we have more data.",
            "japanese": "そのアイデアは一旦置いて、___の時に戻りましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
    ],
    "negotiation": [
        {
            "id": "neg-001",
            "template": "We'd like to propose ___.",
            "example": "We'd like to propose a 15% volume discount for orders over 1,000 units.",
            "japanese": "___を提案させていただきたいのですが。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "neg-002",
            "template": "Would you be open to ___?",
            "example": "Would you be open to extending the payment terms to net 60?",
            "japanese": "___はご検討いただけますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-003",
            "template": "If we were to ___, would you be willing to ___?",
            "example": "If we were to increase the order quantity, would you be willing to offer a better rate?",
            "japanese": "もし___した場合、___していただけますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-004",
            "template": "I'm afraid that's outside our range. Could we consider ___?",
            "example": "I'm afraid that's outside our range. Could we consider a phased approach instead?",
            "japanese": "申し訳ありませんが、それは当社の範囲外です。___を検討できますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-005",
            "template": "We could meet you halfway on ___ if you ___.",
            "example": "We could meet you halfway on the price if you commit to a two-year contract.",
            "japanese": "___について歩み寄ることは可能ですが、___していただければ。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-006",
            "template": "What would it take for you to ___?",
            "example": "What would it take for you to agree to an exclusive distribution arrangement?",
            "japanese": "___していただくには何が必要でしょうか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-007",
            "template": "I understand your position, but from our perspective ___.",
            "example": "I understand your position, but from our perspective the timeline is too aggressive.",
            "japanese": "お立場は理解しますが、当社の観点からは___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-008",
            "template": "Let me see if I understand correctly: you're proposing that ___.",
            "example": "Let me see if I understand correctly: you're proposing that we split the development costs 60-40.",
            "japanese": "正しく理解できているか確認させてください：___というご提案ですね。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-009",
            "template": "That's a non-starter for us. However, we could consider ___.",
            "example": "That's a non-starter for us. However, we could consider flexible licensing terms.",
            "japanese": "それは受け入れられません。しかし、___は検討可能です。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "neg-010",
            "template": "We have some flexibility on ___, but ___ is firm.",
            "example": "We have some flexibility on delivery dates, but the quality standards are firm.",
            "japanese": "___については柔軟に対応可能ですが、___は譲れません。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-011",
            "template": "I need to consult with my team before committing to ___.",
            "example": "I need to consult with my team before committing to those terms.",
            "japanese": "___にコミットする前にチームと相談する必要があります。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "neg-012",
            "template": "As a gesture of goodwill, we're prepared to ___.",
            "example": "As a gesture of goodwill, we're prepared to waive the setup fee.",
            "japanese": "誠意の表れとして、___する用意があります。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "neg-013",
            "template": "The deal-breaker for us would be ___.",
            "example": "The deal-breaker for us would be any reduction in the warranty period.",
            "japanese": "当社にとっての交渉決裂要因は___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-014",
            "template": "We're willing to sweeten the deal by ___.",
            "example": "We're willing to sweeten the deal by including free maintenance for the first year.",
            "japanese": "___を追加して条件を改善する用意があります。",
            "register": "semi-formal",
            "cefr": "C1",
        },
        {
            "id": "neg-015",
            "template": "Could we explore a win-win scenario where ___?",
            "example": "Could we explore a win-win scenario where both sides share the risk?",
            "japanese": "___というWin-Winのシナリオを検討できますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-016",
            "template": "Let's take some time to review and come back with ___.",
            "example": "Let's take some time to review and come back with a revised proposal by next week.",
            "japanese": "時間をいただき、___をもって戻りましょう。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-017",
            "template": "Subject to ___, we'd be happy to proceed with ___.",
            "example": "Subject to board approval, we'd be happy to proceed with the partnership.",
            "japanese": "___を条件に、___を進めさせていただきます。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "neg-018",
            "template": "I think we can find common ground on ___ if we ___.",
            "example": "I think we can find common ground on pricing if we look at the total contract value.",
            "japanese": "___について共通点を見つけられると思います。___すれば。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-019",
            "template": "Given the current market conditions, we believe ___ is reasonable.",
            "example": "Given the current market conditions, we believe a 5% annual increase is reasonable.",
            "japanese": "現在の市場状況を考慮すると、___が妥当と考えます。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-020",
            "template": "We'd like to formalize the agreement with ___.",
            "example": "We'd like to formalize the agreement with a memorandum of understanding.",
            "japanese": "___をもって合意を正式なものにしたいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-021",
            "template": "I appreciate your flexibility on this. In return, we can offer ___.",
            "example": "I appreciate your flexibility on this. In return, we can offer expedited shipping at no extra cost.",
            "japanese": "この件での柔軟な対応に感謝します。その代わり、___を提供できます。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-022",
            "template": "Let me counter with ___.",
            "example": "Let me counter with a proposal that addresses both our concerns.",
            "japanese": "___で対案を出させてください。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-023",
            "template": "Our bottom line on this is ___.",
            "example": "Our bottom line on this is that we can't go below $50 per unit.",
            "japanese": "この件での当社の最低ラインは___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-024",
            "template": "We're confident that this arrangement will be mutually beneficial because ___.",
            "example": "We're confident that this arrangement will be mutually beneficial because it reduces costs for both parties.",
            "japanese": "この取り決めが双方にとって有益であると確信しています。なぜなら___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "neg-025",
            "template": "Let's shake on it. I'm pleased we could reach an agreement on ___.",
            "example": "Let's shake on it. I'm pleased we could reach an agreement on the joint venture terms.",
            "japanese": "握手しましょう。___について合意に至れて嬉しく思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "neg-026",
            "template": "Before we finalize, there's one more point I'd like to address: ___.",
            "example": "Before we finalize, there's one more point I'd like to address: the intellectual property rights.",
            "japanese": "最終決定の前に、もう一点取り上げたいことがあります：___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-027",
            "template": "We need ___ as a precondition for moving forward.",
            "example": "We need a signed NDA as a precondition for moving forward.",
            "japanese": "先に進むための前提条件として___が必要です。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-028",
            "template": "I'd like to revisit the terms of ___ before signing off.",
            "example": "I'd like to revisit the terms of the SLA before signing off.",
            "japanese": "承認前に___の条件を再確認したいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "neg-029",
            "template": "Provided that ___, we're willing to accept ___.",
            "example": "Provided that the quality benchmarks are met, we're willing to accept the proposed pricing.",
            "japanese": "___を前提に、___を受け入れる用意があります。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "neg-030",
            "template": "Let me walk you through the value proposition: ___.",
            "example": "Let me walk you through the value proposition: our solution saves an average of 30% on operational costs.",
            "japanese": "価値提案をご説明させてください：___。",
            "register": "formal",
            "cefr": "B2",
        },
    ],
    "presentation": [
        {
            "id": "prs-001",
            "template": "Good morning, everyone. Today I'd like to talk about ___.",
            "example": "Good morning, everyone. Today I'd like to talk about our Q3 performance and outlook.",
            "japanese": "皆さん、おはようございます。本日は___についてお話しします。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-002",
            "template": "Let me start by giving you an overview of ___.",
            "example": "Let me start by giving you an overview of the market landscape.",
            "japanese": "まず___の概要からお伝えします。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-003",
            "template": "As you can see from this chart, ___.",
            "example": "As you can see from this chart, revenue has grown 20% year-over-year.",
            "japanese": "このチャートからお分かりのように、___。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "prs-004",
            "template": "This brings me to my next point, which is ___.",
            "example": "This brings me to my next point, which is the importance of customer retention.",
            "japanese": "これは次のポイントにつながります。すなわち___です。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-005",
            "template": "I'd like to draw your attention to ___.",
            "example": "I'd like to draw your attention to the trend in the bottom right corner.",
            "japanese": "___にご注目いただきたいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-006",
            "template": "What's particularly noteworthy is ___.",
            "example": "What's particularly noteworthy is the 40% increase in new customer acquisition.",
            "japanese": "特に注目すべきは___です。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-007",
            "template": "To put it another way, ___.",
            "example": "To put it another way, we're seeing a fundamental shift in consumer behavior.",
            "japanese": "言い換えれば、___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-008",
            "template": "Let me illustrate this with an example: ___.",
            "example": "Let me illustrate this with an example: our pilot program in Tokyo saw a 50% adoption rate.",
            "japanese": "例を挙げて説明しますと：___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-009",
            "template": "In conclusion, I'd like to emphasize that ___.",
            "example": "In conclusion, I'd like to emphasize that innovation is the key to our future growth.",
            "japanese": "結論として、___を強調したいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-010",
            "template": "That's a great question. The short answer is ___.",
            "example": "That's a great question. The short answer is that we're currently in the evaluation phase.",
            "japanese": "素晴らしいご質問です。簡潔に申し上げると___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-011",
            "template": "The data clearly shows that ___.",
            "example": "The data clearly shows that customer satisfaction correlates directly with retention rates.",
            "japanese": "データは___を明確に示しています。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-012",
            "template": "I'd now like to turn to ___, which is ___.",
            "example": "I'd now like to turn to our competitive analysis, which is on the next slide.",
            "japanese": "それでは___に移りたいと思います。これは___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-013",
            "template": "There are three key takeaways from today's presentation: ___.",
            "example": "There are three key takeaways from today's presentation: growth, innovation, and sustainability.",
            "japanese": "本日のプレゼンテーションの要点は3つあります：___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-014",
            "template": "I'm happy to take any questions you might have about ___.",
            "example": "I'm happy to take any questions you might have about the implementation roadmap.",
            "japanese": "___についてご質問があればお受けします。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-015",
            "template": "Looking at this from a different angle, ___.",
            "example": "Looking at this from a different angle, the investment pays for itself within 18 months.",
            "japanese": "別の角度から見ると、___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-016",
            "template": "The implications of this are significant: ___.",
            "example": "The implications of this are significant: we need to pivot our strategy for the APAC region.",
            "japanese": "これの意味合いは重大です：___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "prs-017",
            "template": "Before I move on, does anyone have any questions about ___?",
            "example": "Before I move on, does anyone have any questions about the financial projections?",
            "japanese": "先に進む前に、___についてご質問はありますか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-018",
            "template": "To give you some context, ___.",
            "example": "To give you some context, our industry is expected to grow at 12% CAGR over the next five years.",
            "japanese": "背景をお伝えしますと、___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-019",
            "template": "If we compare ___ with ___, we can see that ___.",
            "example": "If we compare last year's performance with this year's, we can see that efficiency has improved by 25%.",
            "japanese": "___と___を比較すると、___ということが分かります。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-020",
            "template": "I'd like to leave you with this thought: ___.",
            "example": "I'd like to leave you with this thought: the best time to invest in our future is now.",
            "japanese": "最後に皆さんにこの言葉を贈ります：___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "prs-021",
            "template": "Let me break this down into three parts: ___.",
            "example": "Let me break this down into three parts: the problem, the solution, and the expected outcomes.",
            "japanese": "これを3つに分けて説明します：___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-022",
            "template": "The reason this matters is ___.",
            "example": "The reason this matters is that it directly impacts our market share.",
            "japanese": "これが重要な理由は___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-023",
            "template": "As this slide demonstrates, ___.",
            "example": "As this slide demonstrates, there's a clear upward trend in user engagement.",
            "japanese": "このスライドが示すように、___。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-024",
            "template": "I'll address that question in more detail when we get to ___.",
            "example": "I'll address that question in more detail when we get to the implementation section.",
            "japanese": "___のセクションに入った時に、そのご質問に詳しくお答えします。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-025",
            "template": "To wrap up, our next steps are ___.",
            "example": "To wrap up, our next steps are to finalize the budget and begin pilot testing.",
            "japanese": "まとめとして、次のステップは___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "prs-026",
            "template": "What sets us apart from the competition is ___.",
            "example": "What sets us apart from the competition is our proprietary AI technology.",
            "japanese": "競合との差別化要因は___です。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-027",
            "template": "I'd like to highlight the fact that ___.",
            "example": "I'd like to highlight the fact that we exceeded our targets in every region.",
            "japanese": "___という事実を強調したいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "prs-028",
            "template": "This represents a ___ percent increase/decrease compared to ___.",
            "example": "This represents a 30 percent increase compared to the same quarter last year.",
            "japanese": "これは___と比較して___パーセントの増加/減少を示しています。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-029",
            "template": "Moving on to the next section, I'd like to discuss ___.",
            "example": "Moving on to the next section, I'd like to discuss our talent acquisition strategy.",
            "japanese": "次のセクションに移り、___について議論したいと思います。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "prs-030",
            "template": "Thank you for your attention. I'm confident that ___.",
            "example": "Thank you for your attention. I'm confident that together we can achieve these ambitious goals.",
            "japanese": "ご清聴ありがとうございます。___と確信しています。",
            "register": "formal",
            "cefr": "B2",
        },
    ],
    "email": [
        {
            "id": "eml-001",
            "template": "I'm writing to follow up on ___.",
            "example": "I'm writing to follow up on our discussion from last Tuesday.",
            "japanese": "___についてフォローアップのためにご連絡しております。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-002",
            "template": "Please find attached ___.",
            "example": "Please find attached the revised proposal for your review.",
            "japanese": "___を添付いたしますのでご確認ください。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-003",
            "template": "I would appreciate it if you could ___.",
            "example": "I would appreciate it if you could send me the updated figures by Friday.",
            "japanese": "___していただけると幸いです。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-004",
            "template": "I apologize for the delay in ___.",
            "example": "I apologize for the delay in getting back to you regarding the contract.",
            "japanese": "___が遅れましたことをお詫び申し上げます。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-005",
            "template": "Just a quick reminder that ___ is due on ___.",
            "example": "Just a quick reminder that the quarterly report is due on March 31st.",
            "japanese": "___が___までに期限であることをお知らせいたします。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "eml-006",
            "template": "Could you please confirm whether ___?",
            "example": "Could you please confirm whether the meeting time works for your team?",
            "japanese": "___かどうかご確認いただけますか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-007",
            "template": "Further to our conversation, I'd like to ___.",
            "example": "Further to our conversation, I'd like to confirm the key points we agreed on.",
            "japanese": "先日のお話に関連して、___したいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-008",
            "template": "I'm reaching out to inquire about ___.",
            "example": "I'm reaching out to inquire about the availability of your consulting services.",
            "japanese": "___についてお問い合わせいたします。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-009",
            "template": "Please don't hesitate to contact me if you need any further ___.",
            "example": "Please don't hesitate to contact me if you need any further clarification.",
            "japanese": "さらなる___が必要な場合は、遠慮なくご連絡ください。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-010",
            "template": "I wanted to bring to your attention that ___.",
            "example": "I wanted to bring to your attention that the project timeline has been revised.",
            "japanese": "___をお知らせしたくご連絡いたしました。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-011",
            "template": "As per our agreement, ___.",
            "example": "As per our agreement, we will deliver the first milestone by the end of this month.",
            "japanese": "合意に基づき、___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-012",
            "template": "I look forward to hearing from you regarding ___.",
            "example": "I look forward to hearing from you regarding the partnership proposal.",
            "japanese": "___についてのご回答をお待ちしております。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-013",
            "template": "Thank you for bringing ___ to my attention.",
            "example": "Thank you for bringing the billing discrepancy to my attention.",
            "japanese": "___にお気づきいただきありがとうございます。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-014",
            "template": "I regret to inform you that ___.",
            "example": "I regret to inform you that we will need to postpone the launch date.",
            "japanese": "残念ながら___をお伝えしなければなりません。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-015",
            "template": "Would it be possible to reschedule ___ to ___?",
            "example": "Would it be possible to reschedule our meeting to next Wednesday at 3 PM?",
            "japanese": "___を___に変更していただくことは可能でしょうか？",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-016",
            "template": "I'm pleased to confirm that ___.",
            "example": "I'm pleased to confirm that your order has been processed and shipped.",
            "japanese": "___を確認でき嬉しく思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-017",
            "template": "For your reference, I've included ___.",
            "example": "For your reference, I've included the product specifications in the attachment.",
            "japanese": "ご参考までに___を添付しました。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-018",
            "template": "At your earliest convenience, could you ___?",
            "example": "At your earliest convenience, could you review and approve the budget request?",
            "japanese": "お手すきの際に___していただけますか？",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-019",
            "template": "I'd like to take this opportunity to ___.",
            "example": "I'd like to take this opportunity to thank everyone for their hard work on this project.",
            "japanese": "この機会に___したいと思います。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-020",
            "template": "Please be advised that ___.",
            "example": "Please be advised that the office will be closed next Monday for maintenance.",
            "japanese": "___をお知らせいたします。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-021",
            "template": "I'm copying ___ on this email as ___.",
            "example": "I'm copying the legal team on this email as they need to review the terms.",
            "japanese": "___のため、___をCCに入れています。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "eml-022",
            "template": "To clarify my previous email, ___.",
            "example": "To clarify my previous email, the deadline applies to the draft version only.",
            "japanese": "前回のメールを補足いたしますと、___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-023",
            "template": "I trust this email finds you well. I'm writing regarding ___.",
            "example": "I trust this email finds you well. I'm writing regarding the upcoming board meeting.",
            "japanese": "お元気でお過ごしのことと存じます。___の件でご連絡いたします。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-024",
            "template": "Could you loop in ___ on this thread?",
            "example": "Could you loop in the finance team on this thread?",
            "japanese": "このスレッドに___を加えていただけますか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "eml-025",
            "template": "Pending your approval, we will proceed with ___.",
            "example": "Pending your approval, we will proceed with the vendor selection process.",
            "japanese": "ご承認を待って、___を進めさせていただきます。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "eml-026",
            "template": "Many thanks for your prompt response regarding ___.",
            "example": "Many thanks for your prompt response regarding the client inquiry.",
            "japanese": "___に関する迅速なご回答ありがとうございます。",
            "register": "formal",
            "cefr": "B1",
        },
        {
            "id": "eml-027",
            "template": "I've taken the liberty of ___.",
            "example": "I've taken the liberty of drafting a preliminary schedule for the workshop.",
            "japanese": "僭越ながら___させていただきました。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "eml-028",
            "template": "With reference to your request for ___, please note that ___.",
            "example": "With reference to your request for additional resources, please note that the budget has been approved.",
            "japanese": "___のご依頼に関して、___をお知らせします。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-029",
            "template": "Kindly acknowledge receipt of ___ at your convenience.",
            "example": "Kindly acknowledge receipt of the signed contract at your convenience.",
            "japanese": "お手すきの際に___の受領をご確認ください。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "eml-030",
            "template": "Should you have any concerns, please feel free to ___.",
            "example": "Should you have any concerns, please feel free to schedule a call with our support team.",
            "japanese": "ご懸念がございましたら、___してください。",
            "register": "formal",
            "cefr": "B2",
        },
    ],
    "discussion": [
        {
            "id": "dsc-001",
            "template": "In my opinion, ___.",
            "example": "In my opinion, we should prioritize customer experience over cost reduction.",
            "japanese": "私の意見では、___。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "dsc-002",
            "template": "I see your point, but have you considered ___?",
            "example": "I see your point, but have you considered the long-term implications?",
            "japanese": "おっしゃることは分かりますが、___は検討されましたか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-003",
            "template": "I tend to agree with ___ on this, because ___.",
            "example": "I tend to agree with the marketing team on this, because the data supports their approach.",
            "japanese": "この件では___に賛成する傾向があります。なぜなら___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-004",
            "template": "While I understand the rationale, I'm concerned about ___.",
            "example": "While I understand the rationale, I'm concerned about the potential impact on employee morale.",
            "japanese": "その理由は理解しますが、___が懸念されます。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-005",
            "template": "That raises an interesting point about ___.",
            "example": "That raises an interesting point about the scalability of our current infrastructure.",
            "japanese": "それは___について興味深い論点を提起しています。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-006",
            "template": "From a practical standpoint, I think ___.",
            "example": "From a practical standpoint, I think we should start with a pilot program.",
            "japanese": "実務的な観点からは、___と思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-007",
            "template": "I'd like to push back on ___ because ___.",
            "example": "I'd like to push back on that assumption because our customer survey tells a different story.",
            "japanese": "___に反論したいのですが、理由は___。",
            "register": "semi-formal",
            "cefr": "C1",
        },
        {
            "id": "dsc-008",
            "template": "Can we look at this from the customer's perspective? ___.",
            "example": "Can we look at this from the customer's perspective? They value reliability over speed.",
            "japanese": "顧客の視点から考えてみませんか？___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-009",
            "template": "I'm not entirely sure I follow. Could you clarify what you mean by ___?",
            "example": "I'm not entirely sure I follow. Could you clarify what you mean by 'agile transformation'?",
            "japanese": "完全には理解できていないのですが。___とはどういう意味でしょうか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-010",
            "template": "To play devil's advocate, what if ___?",
            "example": "To play devil's advocate, what if the market shifts in the opposite direction?",
            "japanese": "あえて反論すると、___の場合はどうでしょうか？",
            "register": "semi-formal",
            "cefr": "C1",
        },
        {
            "id": "dsc-011",
            "template": "There's a strong case to be made for ___.",
            "example": "There's a strong case to be made for investing in renewable energy.",
            "japanese": "___には十分な根拠があります。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-012",
            "template": "I'd argue that ___ is more important than ___ in this context.",
            "example": "I'd argue that speed to market is more important than perfection in this context.",
            "japanese": "この文脈では___の方が___より重要だと主張したいです。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-013",
            "template": "The evidence suggests that ___.",
            "example": "The evidence suggests that remote work actually improves productivity.",
            "japanese": "証拠は___ことを示唆しています。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-014",
            "template": "Let's weigh the pros and cons of ___.",
            "example": "Let's weigh the pros and cons of outsourcing the entire IT function.",
            "japanese": "___のメリットとデメリットを比較検討しましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-015",
            "template": "One thing we haven't considered is ___.",
            "example": "One thing we haven't considered is the regulatory implications in different markets.",
            "japanese": "まだ検討していないのは___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-016",
            "template": "I respectfully disagree. My view is that ___.",
            "example": "I respectfully disagree. My view is that we should invest more in employee training.",
            "japanese": "失礼ですが、同意しかねます。私の考えでは___。",
            "register": "formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-017",
            "template": "That's a fair point. Building on that, I'd add ___.",
            "example": "That's a fair point. Building on that, I'd add that we also need to consider scalability.",
            "japanese": "もっともなご意見です。それに加えて、___を付け加えたいと思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-018",
            "template": "If I may offer a different perspective, ___.",
            "example": "If I may offer a different perspective, the problem isn't the technology but the process.",
            "japanese": "別の視点を提供させていただければ、___。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "dsc-019",
            "template": "I think we're overcomplicating this. Simply put, ___.",
            "example": "I think we're overcomplicating this. Simply put, we need to reduce costs and increase revenue.",
            "japanese": "これを複雑に考えすぎていると思います。簡単に言えば、___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-020",
            "template": "Let me summarize the key arguments: for ___, against ___.",
            "example": "Let me summarize the key arguments: for expansion we have market demand, against we have resource constraints.",
            "japanese": "主な議論をまとめましょう：賛成は___、反対は___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-021",
            "template": "Based on my experience, ___ tends to ___.",
            "example": "Based on my experience, rushing into new markets tends to backfire.",
            "japanese": "私の経験では、___は___傾向があります。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-022",
            "template": "We seem to be aligned on ___. Where we differ is ___.",
            "example": "We seem to be aligned on the goal. Where we differ is the approach.",
            "japanese": "___については一致しているようです。異なるのは___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-023",
            "template": "What are the potential risks if we go with ___?",
            "example": "What are the potential risks if we go with the aggressive expansion strategy?",
            "japanese": "___を選んだ場合の潜在的リスクは何でしょうか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "dsc-024",
            "template": "I think we need more data before deciding on ___.",
            "example": "I think we need more data before deciding on the pricing strategy.",
            "japanese": "___を決定する前に、もっとデータが必要だと思います。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "dsc-025",
            "template": "Let's not lose sight of the fact that ___.",
            "example": "Let's not lose sight of the fact that our customers are our top priority.",
            "japanese": "___という事実を見失わないようにしましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
    ],
    "general": [
        {
            "id": "gen-001",
            "template": "I'd be happy to help you with ___.",
            "example": "I'd be happy to help you with the onboarding process for the new team members.",
            "japanese": "___のお手伝いをさせていただきます。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-002",
            "template": "Could you keep me posted on ___?",
            "example": "Could you keep me posted on the progress of the infrastructure upgrade?",
            "japanese": "___の進捗を教えていただけますか？",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-003",
            "template": "I'll make sure to ___ by the end of ___.",
            "example": "I'll make sure to finalize the report by the end of this week.",
            "japanese": "___までに___するようにします。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-004",
            "template": "Going forward, I suggest that we ___.",
            "example": "Going forward, I suggest that we hold weekly sync-ups instead of daily ones.",
            "japanese": "今後は___することを提案します。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-005",
            "template": "I wanted to give you a heads-up about ___.",
            "example": "I wanted to give you a heads-up about the upcoming audit next month.",
            "japanese": "___について事前にお知らせしたかったのですが。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-006",
            "template": "Let me get back to you on ___ once I've ___.",
            "example": "Let me get back to you on the budget once I've reviewed the latest numbers.",
            "japanese": "___してから___についてお返事します。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-007",
            "template": "I'd like to flag ___ as a potential issue.",
            "example": "I'd like to flag the supply chain delays as a potential issue for our Q4 targets.",
            "japanese": "___を潜在的な問題として指摘したいと思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-008",
            "template": "Let's touch base on ___ next week.",
            "example": "Let's touch base on the marketing campaign results next week.",
            "japanese": "来週___について打ち合わせましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-009",
            "template": "I've been meaning to ask you about ___.",
            "example": "I've been meaning to ask you about the new compliance requirements.",
            "japanese": "___についてお聞きしたいと思っていました。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-010",
            "template": "I appreciate you taking the time to ___.",
            "example": "I appreciate you taking the time to mentor the junior developers.",
            "japanese": "___にお時間をいただきありがとうございます。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-011",
            "template": "It's worth noting that ___.",
            "example": "It's worth noting that our competitors have already adopted this technology.",
            "japanese": "___は注目に値します。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-012",
            "template": "I'd recommend that we ___ before ___.",
            "example": "I'd recommend that we conduct a thorough review before making any changes.",
            "japanese": "___する前に___することをお勧めします。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-013",
            "template": "Can I run something by you? I'm thinking about ___.",
            "example": "Can I run something by you? I'm thinking about reorganizing the team structure.",
            "japanese": "ちょっとご相談があるのですが。___を考えているのですが。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-014",
            "template": "I'll take ownership of ___ and deliver it by ___.",
            "example": "I'll take ownership of the customer feedback analysis and deliver it by next Friday.",
            "japanese": "___を担当し、___までに納品します。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-015",
            "template": "That's outside my area of expertise, but I can connect you with ___.",
            "example": "That's outside my area of expertise, but I can connect you with our legal team.",
            "japanese": "それは私の専門外ですが、___におつなぎできます。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-016",
            "template": "We need to be mindful of ___ when ___.",
            "example": "We need to be mindful of cultural differences when expanding into new markets.",
            "japanese": "___する際に___に注意する必要があります。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-017",
            "template": "I'll loop you in on ___ as soon as ___.",
            "example": "I'll loop you in on the project details as soon as we get the green light.",
            "japanese": "___になり次第、___についてお知らせします。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-018",
            "template": "Would it make sense to ___ instead of ___?",
            "example": "Would it make sense to automate this process instead of doing it manually?",
            "japanese": "___する代わりに___する方が合理的ではないでしょうか？",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-019",
            "template": "I'll defer to ___ on this matter since ___.",
            "example": "I'll defer to the engineering team on this matter since they have the technical expertise.",
            "japanese": "___なので、この件は___に委ねます。",
            "register": "formal",
            "cefr": "C1",
        },
        {
            "id": "gen-020",
            "template": "Let's align on ___ before we proceed.",
            "example": "Let's align on our key objectives before we proceed with the planning.",
            "japanese": "先に進む前に___について認識を合わせましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-021",
            "template": "I'm reaching out because ___.",
            "example": "I'm reaching out because we have an exciting opportunity for collaboration.",
            "japanese": "___のためにご連絡いたしました。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-022",
            "template": "The bottom line is ___.",
            "example": "The bottom line is that we need to increase revenue by 20% this quarter.",
            "japanese": "要するに___ということです。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-023",
            "template": "I'll keep it brief. The key points are ___.",
            "example": "I'll keep it brief. The key points are timeline, budget, and resource allocation.",
            "japanese": "手短に申し上げます。要点は___です。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-024",
            "template": "As a follow-up to ___, I'd like to ___.",
            "example": "As a follow-up to our last meeting, I'd like to share the updated timeline.",
            "japanese": "___のフォローアップとして、___したいと思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-025",
            "template": "I have some concerns about ___, specifically ___.",
            "example": "I have some concerns about the timeline, specifically the testing phase.",
            "japanese": "___について懸念があります。特に___。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-026",
            "template": "Let me know if there's anything I can do to support ___.",
            "example": "Let me know if there's anything I can do to support the product launch.",
            "japanese": "___をサポートするためにできることがあればお知らせください。",
            "register": "semi-formal",
            "cefr": "B1",
        },
        {
            "id": "gen-027",
            "template": "I think we should leverage ___ to achieve ___.",
            "example": "I think we should leverage our existing partnerships to achieve faster market penetration.",
            "japanese": "___を活用して___を達成すべきだと思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-028",
            "template": "For what it's worth, I think ___.",
            "example": "For what it's worth, I think the conservative approach is the safer bet.",
            "japanese": "参考までに申し上げると、___と思います。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-029",
            "template": "Let's make sure we're on the same page about ___.",
            "example": "Let's make sure we're on the same page about the project scope.",
            "japanese": "___について共通認識を持ちましょう。",
            "register": "semi-formal",
            "cefr": "B2",
        },
        {
            "id": "gen-030",
            "template": "I've been giving some thought to ___, and I believe ___.",
            "example": "I've been giving some thought to our hiring strategy, and I believe we should focus on senior talent.",
            "japanese": "___について考えてきたのですが、___と考えます。",
            "register": "semi-formal",
            "cefr": "B2",
        },
    ],
}
